spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/Jitu-77/distributed-razrorpay-config
      username: Jitu-77
      password: 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
      default-label: main

server.port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
---

spring:
  config:
    activate:
      on-profile: k8s
#disabling discovery service
  cloud:
    discovery:
      enabled: false

    config.server.git:
      uri: ${GIT_CONFIG_REPO}
      username: ${GIT_USERNAME}
      password: ${GIT_PASSWORD}
#as there is o discovery service hece eureka comfig is false for all
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
#service name --zipkin/redis/kafka
#name space -- razorpay-core
# helps to resolve domain name for k8's --svc.cluster.local
management:
  zipkin:
    tracing:
      endpoint: http://zipkin.razorpay-core.svc.cluster.local:9411/api/v2/spans